### ISSUE TITLE
Vignettes: Creating an Obesity ADVS

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#22]
Base the vignette on the [BDS Findings vignette from {admiral}](https://pharmaverse.github.io/admiral/articles/bds_finding.html) (also uses ADVS – lucky us!) but don't duplicate sections that would be identical. See [{admiralpeds} ADVS vignette](https://pharmaverse.github.io/admiralpeds/articles/advs.html) as an example.​

Suggestion on contest/structure:
- Explain what the common obesity endpoints are.​
- Explain how to add them to ADVS using {admiral} tools.​ Could consider criterion flags - we have a brand-new function in {admiral}, [derive_vars_crit_flag()](https://pharmaverse.github.io/admiral/dev/articles/bds_finding.html?q=criterion%20#crit_vars). ​

**Comment by Siddhesh2097** [comment]
Hi @kathrinflunkert  , after our discussion in our last meeting, I think we can include the following in our vignette.

1. Adding **derive_param_bmi**. The reason is that "BMI collected on CRF" / "system calculated BMI" is not considered and we again calculate BMI in ADVS, so it will be good to have this in vignette as well.
2. Additional parameters that we have added , WSTCIR, HIPCIR and BMI.
3. Categorical variables
- CHGCAT for Change in SYSBP, DIABP, PULSE
- BASECAT for BMI baseline categories ( Underweight, Overweight, Obese class I, Obese class II )
- AVALCAT for BMI categories , same as above.

4. The new **derive_vars_crit_flag**  for >= 5%, >= 10%, >= 15% and so on weight reduction

Let me know what you think of the above and if there is anything we missed
