### ISSUE TITLE
Documentation:  Tidy up reference page

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#56]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

![image](https://github.com/user-attachments/assets/1f636062-80d1-4564-a486-5b3043400548)

**Comment by manciniedoardo** [comment]
@pharmaverse/admiralmetabolic any takers? Probably involves updating `_pkgdown.yml`.

**Comment by kiwi5104679** [comment]
May I take it?
Maybe I would need your supports, but I will manage to do it.

Shunsuke

Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________
差出人: Edoardo Mancini ***@***.***>
送信日時: 水曜日, 11月 20, 2024 7:29 午後
宛先: pharmaverse/admiralmetabolic ***@***.***>
Cc: GOTO, SHUNSUKE ***@***.***>; Team mention ***@***.***>
件名: Re: [pharmaverse/admiralmetabolic] Documentation: Tidy up reference page (Issue #56)

@ pharmaverse/admiralmetabolic any takers? Probably involves updating _pkgdown. yml. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are on a team that was mentioned. Message ID: <pharmaverse/admiralmetabolic/issues/56/2488194417@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@pharmaverse/admiralmetabolic<https://urldefense.com/v3/__https://github.com/orgs/pharmaverse/teams/admiralmetabolic__;!!N3hqHg43uw!vXEHs-UW7rniSMVPM6qcvKxR42ndiW-SUWw7hGBUgN8Z7oGD0vZ5VHiZmOGdKFgpZMxy5vy1DGcXBqubwSx-ARPHTXkmtw$> any takers? Probably involves updating _pkgdown.yml.
